name: Snyk Code Test

on:
  push:
    branches:
      - main

jobs:
  snyk_code_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk code test and save output to file
        run: snyk code test --sarif > snyk-code.sarif

      - name: Show SARIF file
        run: cat snyk-code.sarif

      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk-code-sarif
          path: snyk-code.sarif
